server:
  port: 8080
spring:
   rabbitmq:
    addresses: 10.8.2.14:5672
    username: admin
    password: 123456
    listener:
      acknowledge-mode: AUTO
      max-concurrency: 10
      prefetch: 3
      retry:
        enabled: true
        initial-interval: 3000
        max-attempts: 5
        multiplier: 1.5
        max-interval: 50000